# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.network "private_network", ip: "172.10.10.10"
  config.vm.provision "shell",
    path: "../setup/provision.sh",
    env: { "SETUP_DIR" => "/vagrant" }
end
