# Generated by Django 3.0.3 on 2020-05-27 00:54

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_subscribed', models.BooleanField()),
                ('payment_token', models.TextField(null=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'vaulty_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('email_quota', models.IntegerField()),
                ('num_received', models.IntegerField(default=0)),
                ('max_email_size', models.IntegerField()),
                ('storage_quota', models.BigIntegerField()),
                ('storage_used', models.BigIntegerField(default=0)),
                ('last_renewal_time', models.DateTimeField()),
                ('storage_backend', models.CharField(choices=[('dropbox', 'Dropbox'), ('gdrive', 'Gdrive'), ('s3', 'S3')], max_length=30)),
                ('storage_token', models.TextField()),
                ('storage_path', models.TextField()),
                ('is_whitelist_enabled', models.BooleanField()),
                ('whitelist', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vaulty_addresses',
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('alias', models.TextField()),
                ('dest', models.TextField()),
            ],
            options={
                'db_table': 'vaulty_aliases',
            },
        ),
        migrations.CreateModel(
            name='LaunchMailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=255)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('message_id', models.TextField(null=True)),
                ('num_attachments', models.IntegerField()),
                ('total_size', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('error_msg', models.TextField(null=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vaulty_mail',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('log_level', models.IntegerField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('mail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Mail')),
            ],
            options={
                'db_table': 'vaulty_logs',
            },
        ),
    ]
