# Generated by Django 3.0.3 on 2020-05-25 21:54

import os
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    # Simple data migration that creates the superuser once the DB is setup
    def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User

        # VAULTY_WEB_DB_NAME = os.environ.get('VAULTY_WEB_DB_NAME')
        DJANGO_SUPERUSER_USERNAME = os.environ.get('DJANGO_SUPERUSER_USERNAME', 'vaulty')
        DJANGO_SUPERUSER_EMAIL = os.environ.get('DJANGO_SUPERUSER_EMAIL', 'abc@vaulty.net')
        DJANGO_SUPERUSER_PASSWORD = os.environ.get('DJANGO_SUPERUSER_PASSWORD', 'abc123')

        superuser = User.objects.create_superuser(
            username=DJANGO_SUPERUSER_USERNAME,
            email=DJANGO_SUPERUSER_EMAIL,
            password=DJANGO_SUPERUSER_PASSWORD)

        superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]
